sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGZMsCsNpHrS5GtDxQ6
    access-key-secret: ZrpJebfT5jUI8sVDyrhOxeO3gCoBii
    bucket-name: web-hl-springboot-study
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wxa061ebba86bc03b3
    secret: 96f89c1fd3777c605450dfe1e9ad1549